### ISSUE TITLE
H5 files with video features

### ISSUE THREAD

**Issue by qjyyyy** [gabeur/mmt#10]
Thank you for your generous sharing.
I want to know the difference between **‘features.audio’** and **'features_t.audio'** in the H5 file.

**Comment by qjyyyy** [comment]
I see that all H5 files have the same **'features_t.audio'**, so I want to know what it stands for.
and others,like **'features_t.face'**,**'features_t.flow'**,etc

**Comment by gabeur** [comment]
Thanks for your interest in our work.
features_t.flow are used to encode the time in the video [start_time, end_time] from which the features were extracted. Similarly for the other modalities.
But we actually use the [get_feature_timings function](https://github.com/gabeur/mmt/blob/56815f586f4625bf5921e869fc26c78c05dc59de/base/base_dataset.py#L486) to calculate those times, so please disregard the features_t data.
