### ISSUE TITLE
About Dataloader

### ISSUE THREAD

**Issue by fmy266** [gabeur/mmt#16]
Thank you for your generous sharing of your code!
But I meet an issue during running your code directly.
I found that an error was thrown during loading data (AttributeError: 'Dataset' object has no attribute 'value', video_data[f"raw_captions.{i}"].value).
I tried to modify the attribute, but I did not find a proper one.

Thank you!

**Comment by fmy266** [comment]
The issue was solved.
Thanks!

**Comment by menatallh** [comment]
> The issue was solved.
> Thanks!

@fmy266  how did you solve it ?

**Comment by JonnyS1226** [comment]
hi, sorry to bother you, could you tell me how to solve it?

**Comment by JonnyS1226** [comment]
I solved it as it was caused by the incompatible version, run `!pip3 install --upgrade pip && pip3 install h5py=='2.9.0'`.
Anyway, thanks~
