### ISSUE TITLE
How to run code with multiple GPUs

### ISSUE THREAD

**Issue by code10086web** [gabeur/mmt#18]
Hi, friends, when I run the code with the following command. At the same time, I changed "n_gpu: 1" to "n_gpu: 2"  in the LSMDC_full_trainval.json. I get some error messages. I hope you can give me some suggestions. 

### Command
`CUDA_VISIBLE_DEVICES=0,1  python -m train --config configs_pub/eccv20/LSMDC_full_trainval.json
`

### Error
![image](https://user-images.githubusercontent.com/53412966/130308556-fa0a2672-fdda-4405-9fa9-ea0b141f5b7c.png)

**Comment by gabeur** [comment]
The code we provided is single GPU. Our experiments last less than 4 hours on a single V100 GPU.
If you want to implement multi GPU, we recommend using the torch.nn.parallel.DistributedDataParallel method.
