### ISSUE TITLE
Can not download activity-net dataset

### ISSUE THREAD

**Issue by kaizhang1215** [gabeur/mmt#23]
wget http://pascal.inrialpes.fr/data2/vgabeur/video-features/activity-net.tar.gz
report 404 not Found
How can I get this dataset, thanks

**Comment by gabeur** [comment]
indeed, we had an issue with our server and the file was unavailable.
The problem should be solved now.

**Comment by kaizhang1215** [comment]
It works! Thanks for your reply.
