### ISSUE TITLE
Cannot download the extracted features

### ISSUE THREAD

**Issue by shuxjweb** [gabeur/mmt#24]
wget http://pascal.inrialpes.fr/data2/vgabeur/video-features/MSRVTT.tar.gz
wget http://pascal.inrialpes.fr/data2/vgabeur/video-features/activity-net.tar.gz
wget http://pascal.inrialpes.fr/data2/vgabeur/video-features/LSMDC.tar.gz

The above links are not available.  ERROR 502: Server UnReachable.

**Comment by gabeur** [comment]
Indeed there is a scheduled power shutdown of our server this weekend. It should be back on Monday.
