### ISSUE TITLE
[CLS] [SEP] bug

### ISSUE THREAD

**Issue by dzabraev** [gabeur/mmt#3]
https://github.com/gabeur/mmt/blob/ef81f96f3a77db273b247c4b60194edefd3e9e52/base/base_dataset.py#L343

The class transformers.tokenization_bert.BertTokenizer does not have `cls_token_ids`. Here must be `cls_token_id`
Due to this mistake all text examples do not have SEP and CLS tokens.

**Comment by gabeur** [comment]
Good catch, thanks!
Fixing this bug seems to improve the results a bit. I will re-run pretraining and finetuning experiments and update the repo once the checkpoints are ready.

**Comment by gabeur** [comment]
I have pushed a fix, re-run the experiments and updated the checkpoints accordingly.
