### ISSUE TITLE
About different dataset partition

### ISSUE THREAD

**Issue by hefeng1995** [gabeur/mmt#4]
Could you provide configs of different data sets, which will make it easier to reproduce the results.

**Comment by gabeur** [comment]
The configurations to reproduce the results reported in the paper are available [here](https://github.com/gabeur/mmt/tree/master/configs_pub/eccv20).

**Comment by hefeng1995** [comment]
What I want to ask is the different divisions of the same data set. For example, the MSRVTT data set, a variety of division have been experimented in the paper, but there is only one division in the open source code.

**Comment by gabeur** [comment]
Indeed, in the paper we have reported results on both 1k-A and 1k-B MSRVTT splits. 
You can reproduce the results for the 1k-A split using [this config](https://github.com/gabeur/mmt/blob/master/configs_pub/eccv20/MSRVTT_jsfusion_trainval.json).
You can reproduce the results for the 1k-B split using [this config](https://github.com/gabeur/mmt/blob/master/configs_pub/eccv20/MSRVTT_miech_trainval.json).
