### ISSUE TITLE
Expert embeddings  and Temporal embeddings

### ISSUE THREAD

**Issue by haoshuai714** [gabeur/mmt#7]
How to generate Expert Embeddings? Generate En(dmodel) according to F n(v) = [F1n... FKn]? ( This part of paper description is not very clear)
Moreover, Temporal Embeddings generated {T1,... How is TD} aligned with F n(v) = [F1n,... FKn]?
For example, D= 8s, and then K=30.

**Comment by gabeur** [comment]
Sorry if the paper was not clear regarding the Expert Embeddings and Temporal Embeddings.

The Expert Embeddings used in MMT are analogous to the Segment Embeddings used in BERT. 
They consist in an embedding table of size N*dmodel that is called ["token_type_embeddings" in the code](https://github.com/gabeur/mmt/blob/56815f586f4625bf5921e869fc26c78c05dc59de/model/bert.py#L81). The parameters of that embedding table are randomly initialized and then jointly optimized to minimize the loss. 

Regarding the Temporal Embeddings, they also consist in an embedding table, of size 32*dmodel that is called ["position_embeddings" in the code](https://github.com/gabeur/mmt/blob/56815f586f4625bf5921e869fc26c78c05dc59de/model/bert.py#L79). There are 30 embeddings for encoding the temporal features, and two additional temporal embeddings Tagg and Tunk, which encode aggregated features and unknown temporal information features (for experts whose temporal information is unknown), respectively.
Each expert feature that has been extracted in the time range [t, t+ 1) will be temporally embedded with Tt+1. For example, a feature extracted at 7.4s in the video will be temporally encoded with temporal embedding T8. 
The extraction times are defined using [this function](https://github.com/gabeur/mmt/blob/56815f586f4625bf5921e869fc26c78c05dc59de/base/base_dataset.py#L357).
The discretisation of the timestep takes place [here](https://github.com/gabeur/mmt/blob/56815f586f4625bf5921e869fc26c78c05dc59de/model/model.py#L519)
