### ISSUE TITLE
HowTo100M pre-processd version 

### ISSUE THREAD

**Issue by aaaa7788** [gabeur/mmt#8]
Sorry to bother again. 
How can I pre-train my own model in HowTo100M dataset? Is there any chance that you release the processd dataset sometime?

**Comment by gabeur** [comment]
Sorry, we do not plan to release the pre-extracted features on the HowTo100M dataset. In order to pre-train your own model on this dataset you will need to extract the features yourself.

**Comment by aaaa7788** [comment]
ok, thanks again.
