### ISSUE TITLE
video features for youcook2 and didemo dataset

### ISSUE THREAD

**Issue by Moymix** [gabeur/mmt#9]
Thank you for sharing your great work ^_^

Could you kindly provide the video features for youcook2 and didemo dataset?

**Comment by gabeur** [comment]
We did not experiment with YouCook2 and DiDeMo datasets in [our ECCV paper](https://arxiv.org/abs/2007.10639).
However, the organisers of the CVPR 2020 Video Pentathlon Challenge have released features for those datasets that should be available [here](https://github.com/albanie/collaborative-experts/blob/master/misc/challenge.md).
